name: Build and Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-dev \
            libgirepository1.0-dev \
            gobject-introspection \
            libwayland-dev \
            meson \
            ninja-build \
            gtk-doc-tools \
            python3 \
            valac \
            libvips \
            libvips-dev \
            pkg-config

      - name: Build gtk4-layer-shell
        run: |
          cd /tmp
          git clone https://github.com/wmww/gtk4-layer-shell
          cd gtk4-layer-shell
          meson setup -Dexamples=false -Ddocs=false -Dtests=false build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig

      - name: Build AMD64
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o walker-amd64 ./cmd

      - name: Build ARM64 with Docker
        run: |
          docker run --rm --platform linux/arm64 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            golang:1.21-bookworm \
            bash -c "
              apt-get update &&
              apt-get install -y libvips-dev libgtk-4-dev libwayland-dev libglib2.0-dev pkg-config gcc libc6-dev &&
              CGO_ENABLED=1 GOOS=linux GOARCH=arm64 go build -o walker-arm64 ./cmd
            "

      - name: Create archives
        run: |
          # Create directories
          mkdir -p dist/walker_${{ steps.version.outputs.VERSION }}_Linux_x86_64
          mkdir -p dist/walker_${{ steps.version.outputs.VERSION }}_Linux_arm64

          # Copy AMD64 files
          cp walker-amd64 dist/walker_${{ steps.version.outputs.VERSION }}_Linux_x86_64/walker
          cp LICENSE dist/walker_${{ steps.version.outputs.VERSION }}_Linux_x86_64/
          cp internal/config/config.default.toml dist/walker_${{ steps.version.outputs.VERSION }}_Linux_x86_64/
          cp -r internal/config/themes dist/walker_${{ steps.version.outputs.VERSION }}_Linux_x86_64/

          # Copy ARM64 files
          cp walker-arm64 dist/walker_${{ steps.version.outputs.VERSION }}_Linux_arm64/walker
          cp LICENSE dist/walker_${{ steps.version.outputs.VERSION }}_Linux_arm64/
          cp internal/config/config.default.toml dist/walker_${{ steps.version.outputs.VERSION }}_Linux_arm64/
          cp -r internal/config/themes dist/walker_${{ steps.version.outputs.VERSION }}_Linux_arm64/

          # Create tarballs
          cd dist
          tar -czf walker_${{ steps.version.outputs.VERSION }}_Linux_x86_64.tar.gz walker_${{ steps.version.outputs.VERSION }}_Linux_x86_64/
          tar -czf walker_${{ steps.version.outputs.VERSION }}_Linux_arm64.tar.gz walker_${{ steps.version.outputs.VERSION }}_Linux_arm64/

      - name: Generate changelog
        id: changelog
        run: |
          if [ -f CHANGELOG.md ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            sed -n "/^## \[${{ steps.version.outputs.VERSION }}\]/,/^## \[/p" CHANGELOG.md | sed '$d' >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=Release ${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: Release ${{ steps.version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
          files: |
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: walker-binaries
          path: |
            walker-amd64
            walker-arm64
