name: Nix

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Set up Cachix
        uses: cachix/cachix-action@v15
        with:
          name: walker
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build default package
        run: nix build -L --extra-substituters "https://walker.cachix.org" .#default
