name: Nix

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Set up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: walker
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build default package
        run: nix build -L .
